In [2]:
import numpy as np

arr = np.array([5,8,3,10])

print(arr)
print(type(arr))

[ 5  8  3 10]
<class 'numpy.ndarray'>


In [8]:
import numpy as np
arr_1 = np.array( [5,8,3,10] )

arr_2=np.array( [6,2,8,11] )

result_addition = arr_1 + arr_2
print(result_addition)

substract_addition = arr_1 - arr_2
print(substract_addition)

multiply_result = arr_1 * arr_2
print(multiply_result)

[11 10 11 21]
[-1  6 -5 -1]
[ 30  16  24 110]


In [9]:
devision_result = arr_1 / arr_2
print(devision_result)

[0.83333333 4.         0.375      0.90909091]


In [10]:
arr_1 = np.array([16,9,36,100])
print(np.sqrt(arr_1))

[ 4.  3.  6. 10.]


In [11]:
print(np.sum(arr_1))

161
