In [2]:
import numpy as np

arr = np.array([5,8,3,10])

print(arr)
print(type(arr))

[ 5  8  3 10]
<class 'numpy.ndarray'>


In [8]:
import numpy as np
arr_1 = np.array( [5,8,3,10] )

arr_2=np.array( [6,2,8,11] )

result_addition = arr_1 + arr_2
print(result_addition)

substract_addition = arr_1 - arr_2
print(substract_addition)

multiply_result = arr_1 * arr_2
print(multiply_result)

[11 10 11 21]
[-1  6 -5 -1]
[ 30  16  24 110]


In [9]:
devision_result = arr_1 / arr_2
print(devision_result)

[0.83333333 4.         0.375      0.90909091]


In [10]:
arr_1 = np.array([16,9,36,100])
print(np.sqrt(arr_1))

[ 4.  3.  6. 10.]


In [12]:
print(np.sum(arr_1))
print(np.max(arr_1))
print(np.min(arr_2))

161
100
2


In [16]:
arr_1 = np.array([[9, 10,5],[8,12,20]])
print(arr_1)
print(arr_1.size)
print(arr_1.ndim)
print(arr_1.shape)


[[ 9 10  5]
 [ 8 12 20]]
6
2
(2, 3)


In [20]:
arr_1 = np.array([[[9, 10,5],[8,12,20]],[[1,2,3],[4,5,6]]])
print(arr_1)
print(arr_1.size)
print(arr_1.ndim)
print(arr_1.shape)

[[[ 9 10  5]
  [ 8 12 20]]

 [[ 1  2  3]
  [ 4  5  6]]]
12
3
(2, 2, 3)


In [ ]:
array = np.array([1,2,3,True])
print(array.dtype)

<U21


In [33]:
arr_2 = np.array([[1,2,3],[4,5,6]])
print(arr_2[1, 2])  # Accessing element at row 1, column 2

6


In [34]:
arr = np.array([30, 20, 10, 40, 50])    
condition = arr > 25
print(condition)  # Output: [ True False False  True  True]

[ True False False  True  True]


In [35]:
print(arr[condition])  # Output: [30 40 50]

[30 40 50]


In [44]:
arr_1 = np.array([30, 20, 10, 40, 50])
print(arr_1[(arr_1 > 25) & (arr_1 < 45)])

[30 40]


In [63]:
arr = np.array([
	            [31,30,28],
				[29,29,32],
				[26,24,27],
				[31,34,35],
				[28,31,30]
				])

daily_average = np.mean(arr)
print(daily_average)

print(arr[arr > daily_average])

29.666666666666668
[31 30 32 31 34 35 31 30]
