In [2]:
import numpy as np

arr = np.array([5,8,3,10])

print(arr)
print(type(arr))

[ 5  8  3 10]
<class 'numpy.ndarray'>


In [8]:
import numpy as np
arr_1 = np.array( [5,8,3,10] )

arr_2=np.array( [6,2,8,11] )

result_addition = arr_1 + arr_2
print(result_addition)

substract_addition = arr_1 - arr_2
print(substract_addition)

multiply_result = arr_1 * arr_2
print(multiply_result)

[11 10 11 21]
[-1  6 -5 -1]
[ 30  16  24 110]


In [9]:
devision_result = arr_1 / arr_2
print(devision_result)

[0.83333333 4.         0.375      0.90909091]


In [10]:
arr_1 = np.array([16,9,36,100])
print(np.sqrt(arr_1))

[ 4.  3.  6. 10.]


In [12]:
print(np.sum(arr_1))
print(np.max(arr_1))
print(np.min(arr_2))

161
100
2


In [16]:
arr_1 = np.array([[9, 10,5],[8,12,20]])
print(arr_1)
print(arr_1.size)
print(arr_1.ndim)
print(arr_1.shape)


[[ 9 10  5]
 [ 8 12 20]]
6
2
(2, 3)


In [20]:
arr_1 = np.array([[[9, 10,5],[8,12,20]],[[1,2,3],[4,5,6]]])
print(arr_1)
print(arr_1.size)
print(arr_1.ndim)
print(arr_1.shape)

[[[ 9 10  5]
  [ 8 12 20]]

 [[ 1  2  3]
  [ 4  5  6]]]
12
3
(2, 2, 3)


In [ ]:
array = np.array([1,2,3,True])
print(array.dtype)

<U21


In [33]:
arr_2 = np.array([[1,2,3],[4,5,6]])
print(arr_2[1, 2])  # Accessing element at row 1, column 2

6


In [34]:
arr = np.array([30, 20, 10, 40, 50])    
condition = arr > 25
print(condition)  # Output: [ True False False  True  True]

[ True False False  True  True]


In [35]:
print(arr[condition])  # Output: [30 40 50]

[30 40 50]


In [44]:
arr_1 = np.array([30, 20, 10, 40, 50])
print(arr_1[(arr_1 > 25) & (arr_1 < 45)])

[30 40]


In [63]:
arr = np.array([
	            [31,30,28],
				[29,29,32],
				[26,24,27],
				[31,34,35],
				[28,31,30]
				])

daily_average = np.mean(arr)
print(daily_average)

print(arr[arr > daily_average])

29.666666666666668
[31 30 32 31 34 35 31 30]


In [ ]:
print(np.zeros(5))  # Creates an array of zeros with 5 elements


[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [67]:
print(np.zeros((2,3)))  # Creates a 2x3 array of zeros

[[0. 0. 0.]
 [0. 0. 0.]]


In [68]:
print(np.ones(5))  # Creates an array of ones with 5 elements

[1. 1. 1. 1. 1.]


In [69]:
print(np.ones((2,3)))  # Creates a 2x3 array of ones

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.full((2,3), 7)) # Creates a 2x3 array filled with the value 7

[[7 7 7]
 [7 7 7]]


In [ ]:
print(np.full((2,3), (1,2,3))) 

[[1 2 3]
 [1 2 3]]


In [78]:
print(np.empty((2,3))) 

[[4.9e-324 9.9e-324 1.5e-323]
 [4.9e-324 9.9e-324 1.5e-323]]


In [80]:
import pandas as pd

In [85]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35 , 40]
    }
df = pd.DataFrame(data)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40


In [86]:
print(df.loc[0 , 'Name'])  # Accessing the 'Name' column of the first row

Alice


In [ ]:
print(df.iloc[2, 1]) # Accessing the 'Age' column of the third row. This will return the value 35.

35


In [88]:
print(df.loc[2])

Name    Charlie
Age          35
Name: 2, dtype: object


In [90]:
print(df.iloc[2]) 

Name    Charlie
Age          35
Name: 2, dtype: object


In [24]:
df = pd.DataFrame(data,index=["student1", "student2", "student3", "student4"])
print(df)

             Name  Age
student1    Alice   25
student2      Bob   30
student3  Charlie   35
student4    David   40


In [105]:
print(df.iloc[1]) 
print(df.loc['student3'])


Name    Bob
Age      30
Name: student2, dtype: object
Name    Charlie
Age          35
Name: student3, dtype: object


In [112]:
print(df.loc[["student2","student4"]])  


           Name  Age
student2    Bob   30
student4  David   40


In [111]:
age_column = df['Age']
print(age_column)  

student1    25
student2    30
student3    35
student4    40
Name: Age, dtype: int64


In [116]:
print(df.columns) # Accessing the columns of the DataFrame
print(list(df.columns))  # Convert Index object to a list

Index(['Name', 'Age'], dtype='object')
['Name', 'Age']


In [119]:
print(df.size) # Returns the total number of elements in the DataFrame
print(df.shape)  # Returns the shape of the DataFrame (rows, columns)
print(len(df))  # Returns the number of rows in the DataFrame

8
(4, 2)
4


In [14]:
print(df.values)  
print(type(df.values)) 

[['Alice' 25]
 ['Bob' 30]
 ['Charlie' 35]
 ['David' 40]]
<class 'numpy.ndarray'>


In [16]:
print(df['Age'].mean()) # Returns the mean of the 'Age' column                                  
print(df['Age'].sum())  # Returns the sum of each column

32.5
130


In [37]:
df['City'] = ['Colombo', 'Kandy', 'Galle', 'Matara']
df['Salary'] = [50000, 60000, 70000, 80000]  # Adding a new 'Salary' column
print(df)  # Display the updated DataFrame with the new 'city' column

             Name  Age     City  Salary
student1    Alice   25  Colombo   50000
student2      Bob   30    Kandy   60000
student3  Charlie   35    Galle   70000
student4    David   40   Matara   80000


In [30]:
filtered_df = df[df['Age'] > 30]  # Filtering rows where 'Age' is greater than 30
print(filtered_df)  # Display the filtered DataFrame
print(type(filtered_df))  # Display the type of the filtered DataFrame

             Name  Age    City  Salary
student3  Charlie   35   Galle   70000
student4    David   40  Matara   80000
<class 'pandas.core.frame.DataFrame'>


In [36]:
filtered_df = df[(df['Age'] > 28) & (df['Salary'] < 65000)] 
print(filtered_df) 

         Name  Age   City  Salary
student2  Bob   30  Kandy   60000


In [53]:
data = {
    'Name': ['Ayesha', 'Nimal', 'Tharindu', 'Kasun','Shashini'],
    'Assignment1': [78,65,88,50,80],
    'Assignment2': [85,70,90,45,75],
    'FinalExam': [90,72,95,60,85]
    }
df = pd.DataFrame(data)
print(df)

       Name  Assignment1  Assignment2  FinalExam
0    Ayesha           78           85         90
1     Nimal           65           70         72
2  Tharindu           88           90         95
3     Kasun           50           45         60
4  Shashini           80           75         85


In [54]:
df = pd.DataFrame(data,index=["1001", "1002", "1003", "1004", "1005"])
print(df)

          Name  Assignment1  Assignment2  FinalExam
1001    Ayesha           78           85         90
1002     Nimal           65           70         72
1003  Tharindu           88           90         95
1004     Kasun           50           45         60
1005  Shashini           80           75         85


In [69]:
max_final_filtered_df = df[df['FinalExam'] > 80] 
print(max_final_filtered_df[['Name', 'FinalExam']]) 

          Name  FinalExam
1001    Ayesha         90
1003  Tharindu         95
1005  Shashini         85


In [71]:
df['Average'] = (df["Assignment1"] + df["Assignment2"] + df["FinalExam"]) / 3
print(df)

          Name  Assignment1  Assignment2  FinalExam    Average
1001    Ayesha           78           85         90  84.333333
1002     Nimal           65           70         72  69.000000
1003  Tharindu           88           90         95  91.000000
1004     Kasun           50           45         60  51.666667
1005  Shashini           80           75         85  80.000000


In [73]:
average_max_df= df['Average'].max()
max_average_df = df[df['Average'] == average_max_df]
print(max_average_df[['Name', 'Average']])

          Name  Average
1003  Tharindu     91.0


In [ ]:
total = df['Assignment1'].sum()
print("Total Assignment1 marks:", total)

Total Assignment1 marks: 361
